config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
  }

  devise_scope :user do
    root  "homes#top"
    post  "users/guest_sign_in" => "users/sessions#create_guest", as: "user_guest_session"
  end

  get   "/users/:id/posts"        => "users#posts",       as: "users_posts"
  get   "/users/:id/recipes"      => "users#recipes",     as: "users_recipes"
  get   "/users/:id/withdrawal"   => "users#withdrawal",  as: "users_withdrawal"
  patch "/users/:id/unsubscribe"  => "users#unsubscribe", as: "users_unsubscribe"
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts
  resources :recipes
  resources :comments,        only: [:create, :destroy]
  resources :foods,           only: [:create, :destroy]
  resources :flows,           only: [:create, :destroy]
  resources :favorites,       only: [:create, :destroy]
  resources :bookmarks,       only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :items,           only: [:create, :update, :destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to  :user
  belongs_to  :post,    optional: true
  belongs_to  :recipe,  optional: true

  def favorite_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def fovorite_by(user)
    favorites.where(user_id: user.id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user, only: [:destroy]

  def create
    # Postにいいねする場合の処理
    if params[:base_type] == "post"
      @favorite_base = Post.find(params[:favorite_base_id])
      @favorite = Favorite.new(user_id: current_user.id, post_id: @favorite_base.id)

    # Recipeにいいねする場合の処理
    else
      @favorite_base = Recipe.find(params[:favorite_base_id])
      @favorite = Favorite.new(user_id: current_user.id, recipe_id: @favorite_base.id)
    end

    @favorite.save
  end

  def destroy
    # Postのいいねを削除する場合の処理
    if params[:base_type] == "post"
      @favorite_base = Post.find(params[:favorite_base_id])
      @favorite = @favorite_base.favorited_by(current_user)

    # Recipeのいいねを削除する場合の処理
    else
      @favorite_base = Recipe.find(params[:favorite_base_id])
      @favorite = @favorite_base.favorited_by(current_user)
    end

    @favorite.destroy
  end

  private

  # いいね削除実行ユーザーが対象のいいね作成ユーザーと同一であることの確認
  def check_user
    favorite = Favorite.find(params[:id])
    user = User.find(favorite.user_id)
    redirect_back fallback_location: user_path(current_uer.id) unless user == current_user
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<%# ログイン時いいね機能をON %>
<% if user_signed_in? %>

  <%# いいね既済の場合destroyアクションへのリンクを付与 %>
  <% if favorite_base.favorited_by?(current_user) %>
    <%= link_to favorite_path(favorite_base.favorited_by(current_user), favorite_base_id: favorite_base.id, base_type: base_type(favorite_base)), method: :delete, remote: true do %>
      <p class="d-inline-block">
        <i class="fas fa-heart fa-lg fa-pink"></i>
        <%= favorite_base.favorite_users.count %>件
      </p>
    <% end %>

  <%# いいね未済の場合createアクションへのリンクを付与 %>
  <% else %>
    <%= link_to favorites_path(favorite_base_id: favorite_base.id, base_type: base_type(favorite_base)), method: :post, remote: true do %>
      <p class="d-inline-block">
        <i class="far fa-heart fa-lg fa-pink"></i>
        <%= favorite_base.favorite_users.count %>件
      </p>
    <% end %>
  <% end %>

<%# 未ログイン時いいね機能をOFFにし、いいねの数のみ表示 %>
<% else %>
    <p class="d-inline-block">
      <i class="fas fa-heart fa-lg fa-pink"></i>
      <%= favorite_base.favorite_users.count %>件
    </p>
<% end %>

app/views/favorites/create.js.erb
<%# いいね登録 %>
$('.favorite_<%= @favorite_base.id %>').html("<%= j(render "favorites/favorite", favorite_base: @favorite_base) %>")

app/views/favorites/destroy.js.erb
<%# いいね解除 %>
$('.favorite_<%= @favorite_base.id %>').html("<%= j(render "favorites/favorite", favorite_base: @favorite_base) %>")