config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
  }

  devise_scope :user do
    root  "homes#top"
    post  "users/guest_sign_in" => "users/sessions#create_guest", as: "user_guest_session"
  end

  get   "/users/:id/posts"        => "users#posts",       as: "users_posts"
  get   "/users/:id/recipes"      => "users#recipes",     as: "users_recipes"
  get   "/users/:id/withdrawal"   => "users#withdrawal",  as: "users_withdrawal"
  patch "/users/:id/unsubscribe"  => "users#unsubscribe", as: "users_unsubscribe"
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts
  resources :recipes
  resources :comments,        only: [:create, :destroy]
  resources :foods,           only: [:create, :destroy]
  resources :flows,           only: [:create, :destroy]
  resources :favorites,       only: [:create, :destroy]
  resources :bookmarks,       only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :items,           only: [:create, :update, :destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  acts_as_taggable

  mount_uploaders :recipe_images, RecipeImagesUploader

  belongs_to  :user

  has_many    :favorites,       dependent: :destroy
  has_many    :comments,        dependent: :destroy
  has_many    :bookmarks,       dependent: :destroy
  has_many    :foods,           dependent: :destroy
  has_many    :flows,           dependent: :destroy
  has_many    :favorite_users,  through: :favorites, source: :user
  has_many    :bookmark_users,  through: :bookmarks, source: :user

  validates   :recipe_images, :footprint, :status, presence: true
  validates   :title, presence: true, length: { maximum: 20 }
  validates   :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def favorited_by(user)
    favorites.find_by(user_id: user.id)
  end

  def bookmark_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def bookmark_by(user)
    bookmarks.find_by(user_id: user.id)
  end

  enum status: { "非公開": false, "公開": true }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.where(status: "公開")
    @tags = @recipes.tag_counts_on(:tags)

    if params[:search]

      if params[:search].present?
        @title = "検索結果：#{params[:search]}"
        @recipes = @recipes.where("title LIKE ?", "%#{params[:search]}%").order(id: "DESC").page(params[:page]).per(12)
      else
        @title = "検索結果がありません"
      end

    elsif params[:bookmarks]
      @recipes = current_user.bookmark_recipe

      if current_user.bookmark_recipe.present?
        @title = "ブックマーク"
      else
        @title = "ブックマークがありません"
      end

    elsif params[:tag_name]
      @recipes = @recipes.tagged_with("#{params[:tag_name]}")
      @title = "検索結果：#{params[:tag_name]}"

    else
      @title = "ALL"
    end

    @recipes = @recipes.order(id: "DESC").page(params[:page]).per(12)
  end

  def show
    @recipe = Recipe.find(params[:id])
    if @recipe.status == "公開" || @recipe.user_id == current_user.id
      @footprint = @recipe.footprint
      if user_signed_in?
        @footprint += 1 unless @recipe.user_id == current_user.id
      end
      @recipe.update(footprint: @footprint)
      @foods = Food.where(recipe_id: @recipe.id)
      @flows = Flow.where(recipe_id: @recipe.id)
      @comments = Comment.where(recipe_id: @recipe.id)

      if @recipe.status == "非公開"
        flash.now[:error] = "非公開のページです"
      end
    elsif @recipe.status == "非公開"
      flash[:error] = "非公開のページです"
      redirect_to recipes_path
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    result = false

    if recipe_params[:recipe_images].present?
      result = Vision.get_image_data(@recipe.recipe_images[0].url)
    else
      result = true
    end

    if result.blank?
      flash.now[:error] = "画像が不適切です"
      render "new"
      return
    end

    if @recipe.save
      flash[:success] = "フォーマットが作成されました"
      redirect_to edit_recipe_path(@recipe.id)
    else
      flash.now[:error] = "保存に失敗しました"
      render "new"
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @foods = Food.where(recipe_id: @recipe.id)
    @flows = Flow.where(recipe_id: @recipe.id)
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.recipe_images = recipe_params[:recipe_images]
    @foods = Food.where(recipe_id: @recipe.id)
    @flows = Flow.where(recipe_id: @recipe.id)
    result = false

    if recipe_params[:recipe_images].present?
      result = Vision.get_image_data(@recipe.recipe_images[0].url)
    else
      result = true
    end

    if result.blank?
      flash.now[:error] = "画像が不適切です"
      render "edit"
      return
    end

    if @recipe.flows.present? && @recipe.foods.present?

      if @recipe.update(recipe_params)
        @recipe.update(status: "公開")
        flash[:success] = "編集を保存しました"
        redirect_to recipe_path(@recipe.id)
      else
        flash.now[:error] = "保存に失敗しました"
        render "edit"
      end

    else

      if @recipe.update(recipe_params)
        @recipe.update(status: "非公開")
        flash[:error] = "材料・手順がないため非公開で保存しました"
        redirect_to recipe_path(@recipe.id)
      else
        flash.now[:error] = "保存に失敗しました"
        render "edit"
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.destroy
      flash[:success] = "削除しました"
      redirect_to recipes_path
    else
      flash[:error] = "削除に失敗しました"
      redirect_to recipe_path(@recipe.id)
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit({ recipe_images: [] }, :title, :body, :status, :tag_list)
  end

  def check_user
    recipe = Recipe.find(params[:id])
    user = User.find(recipe.user_id)
    redirect_back fallback_location: user_path(current_user.id) unless user == current_user
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_index.html.erb
<%# レシピ一覧 %>
<div class="card-box">
  <% recipes.each do |recipe| %>
    <div class="card">
      <%= link_to recipe_path(recipe.id) do %>
        <%= image_tag recipe.recipe_images[0].to_s, size: "200x150", class: "image" %>
      <% end %>

      <p class="card-title mt-3 mb-3"><%= recipe.title %></p>

      <div class="card-icon">
        <div class="favorite_<%= recipe.id %> favorites">
          <%= render "favorites/favorite", favorite_base: recipe %>
        </div>

        <p class="comments">
          <i class="fas fa-comment fa-lg fa-blue"></i>
          <%= recipe.comments.count %>件
        </p>

        <p class="footprints">
          <i class="fas fa-paw fa-lg fa-brown"></i>
          <%= recipe.footprint %>件
        </p>
      </div>

      <div class="user-body">
        <div class="user-body__left">
          <%= link_to user_path(recipe.user_id) do %>
            <%= image_tag recipe.user.user_image.thumb.url, size: "40x40", class: "user-icon" %>
          <% end %>

          <p><%= recipe.user.family_name + recipe.user.given_name %></p>
        </div>

        <div class="user-body__right">
          <div class="relationship_<%= recipe.user.id %> relationships">
            <%= render "relationships/relationship", follower: recipe.user %>
          </div>

          <div class="bookmark_<%= recipe.id %> bookmarks">
            <%= render "bookmarks/bookmark", bookmark_base: recipe %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<%# レシピ編集ページ %>
<main>
  <div class="container">
    <div class="row">
      <h4 class="new-edit__title my-4">レシピ編集</h4>

      <%# ページ上段 %>
      <%= form_with model: @recipe, url: recipe_path(@recipe.id), local: true, class: "new-edit__body col-12 d-flex" do |f| %>

        <%# ページ左上 %>
        <div class="new-edit__left w-50 p-3 mb-4">

          <%# タイトル入力フォーム %>
          <div class="title">
            <%= f.label :title, "タイトル", class: "need" %>
            <%= f.text_field :title, autofocus: true %>
            <% if @recipe.errors.include?(:title) %>
              <span class="red"><%= @recipe.errors.full_messages_for(:title).first %></span>
            <% end %>
          </div>

          <%# 画像投稿フォーム %>
          <div class="img my-4">
            <%= f.label :recipe_images, "写真", class: "need" %>
            <div class="img-box mb-2">
              <%= image_tag @recipe.recipe_images[0].to_s, size: "550x350", class: "main-img img_prev" %>
            </div>
            <button>
              <%= f.file_field :recipe_images, multiple: true, class: "img" %>
            </button>
            <% if @recipe.errors.include?(:recipe_images) %>
              <span class="red"><%= @recipe.errors.full_messages_for(:recipe_images).first %></span>
            <% end %>
          </div>
        </div>

        <%# ページ右上 %>
        <div class="new-edit__right w-50 p-3 mb-4">

          <%# タグ付けフォーム %>
          <div class="tag">
            <%= f.label :tag_list, "タグ" %>
            <%= f.text_field :tag_list, value: @recipe.tag_list.join(','), id: "tags" %>
          </div>

          <%# 詳細入力フォーム %>
          <div class="text my-4">
            <%= f.label :body, "詳細", class: "need" %>
            <%= f.text_area :body, autofocus: true %>
            <% if @recipe.errors.include?(:body) %>
              <span class="red"><%= @recipe.errors.full_messages_for(:body).first %></span>
            <% end %>
          </div>

          <div class="edit-action text-center mb-4">
            <%= f.submit "編集確定", autofocus: true, class: "d-inline-block btn_blue" %>
            <%= link_to "削除", recipe_path(@recipe.id), method: :delete, data: {confirm: "本当に削除しますか"}, class: "d-inline-block btn_red ml-5" %>
          </div>
        </div>
      <% end %>

      <%# ページ下段 %>
      <div class="new-edit__body new-edit__body_under col-12 d-flex mt-5">

        <%# ページ左下 %>
        <div class="new-edit__left w-50 p-3 mb-4">

          <%# 材料入力フォーム %>
          <%= form_with model: @food, url: foods_path do |f| %>
            <%= f.label :name, "材料", class: "need" %>
            <%= f.text_field :name, autofocus: true, class: "food-text" %>
            <%= f.hidden_field :recipe_id, value: @recipe.id %>
            <%= f.submit "追加", class: "btn_blue" %>
          <% end %>

          <div class="food__list mt-5">
            <%= render "foods/food", foods: @foods %>
          </div>
        </div>

        <%# ページ右下 %>
        <div class="new-edit__right w-50 p-3 mb-4">

          <%# 作り方入力フォーム %>
          <%= form_with model: @flow, url: flows_path do |f| %>
            <%= f.label :body, "作り方", class: "need" %>
            <div class="edit-flow__form">
              <%= f.text_area :body, autofocus: true, class: "flow-text ml-0 mr-2" %>
              <%= f.hidden_field :recipe_id, value: @recipe.id %>
              <%= f.submit "追加", class: "btn_blue ml-0" %>
            </div>
          <% end %>

          <div class="flow__list mt-5">
            <%= render "flows/flow", flows: @flows %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/recipes/index.html.erb
<%# レシピ一覧ページ %>
<main class="main__background main__background__recipe">
  <div class="container">
    <div class="row">
      <%# レシピ一覧サイドバー %>
      <div class="sidebar col-12 col-sm-2 bg-white my-3 px-3">
        <%= render "/shared/index_sidebar", tags: @tags %>
      </div>

      <%# レシピ一覧メイン %>
      <div class="post-recipe-index col-12 col-sm-10 my-3 px-3">

        <%# タイトルバー %>
        <div class="titlebar bg-white">
          <h4 class="m-3">Recipes　<%= @title %></h4>
        </div>

        <%# レシピ一覧 %>
        <%= render "index", recipes: @recipes %>
        <%= paginate @recipes %>
      </div>
    </div>
  </div>
</main>

app/views/recipes/new.html.erb
<%# レシピ新規投稿ページ %>
<main>
  <div class="container">
    <div class="row">
      <h4 class="new-edit__title my-4">新規レシピ</h4>

      <%= form_with model: @recipe, url: recipes_path(@recipe.id), local: true, class: "new-edit__body d-flex col-12" do |f| %>

        <%# ページ左側 %>
        <div class="new-edit__left w-50 p-3 mb-4">

          <%# タイトル入力フォーム %>
          <div class="title">
            <%= f.label :title, "タイトル", class: "need" %>
            <%= f.text_field :title, autofocus: true %>
            <% if @recipe.errors.include?(:title) %>
              <span class="red"><%= @recipe.errors.full_messages_for(:title).first %></span>
            <% end %>
          </div>

          <%# 画像投稿フォーム %>
          <div class="img my-4">
            <%= f.label :recipe_images, "写真", class: "need" %>
            <div class="img-box mb-2">
              <%= image_tag @recipe.recipe_images[0].to_s, size: "550x350", class: "main-img img_prev" %>
            </div>
            <button>
              <%= f.file_field :recipe_images, multiple: true, class: "img need_long" %>
            </button>
            <% if @recipe.errors.include?(:recipe_images) %>
              <span class="red"><%= @recipe.errors.full_messages_for(:recipe_images).first %></span>
            <% end %>
          </div>
        </div>

        <%# ページ右側 %>
        <div class="new-edit__right w-50 p-3 mb-4">

          <%# タグ付けフォーム %>
          <div class="tag">
            <%= f.label :tag_list, "タグ" %>
            <%= f.text_field :tag_list, value: @recipe.tag_list.join(','), id: "tags" %>
          </div>

          <%# 本文入力フォーム %>
          <div class="text my-4">
            <%= f.label :body, "詳細", class: "need" %>
            <%= f.text_area :body, autofocus: true %>
            <% if @recipe.errors.include?(:body) %>
              <span class="red"><%= @recipe.errors.full_messages_for(:body).first %></span>
            <% end %>
          </div>

          <%= f.submit "次へ", class: "btn_blue" %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/recipes/show.html.erb
<%# レシピ詳細ページ %>
<main>
  <div class="container">
    <div class="row">

      <%# ページ左側 %>
      <div class="show_left col-12 col-sm-6 mt-3">
        <%= image_tag @recipe.recipe_images[0].to_s, size: "550x350", class: "main-img" %>

        <%# タイトルバー %>
        <div class="show__title">
          <h3><%= @recipe.title %></h3>

          <div class="bookmark_<%= @recipe.id %>">
            <%= render "bookmarks/bookmark", bookmark_base: @recipe %>
          </div>
        </div>

        <%# レシピ投稿ユーザー詳細 %>
        <div class="show__user-body">

          <%# ユーザー詳細左側 %>
          <div class="user-body__left_wrapper d-flex">
            <div class="user-body__left">
              <%= link_to user_path(@recipe.user_id) do %>
                <%= image_tag @recipe.user.user_image.thumb.url, size: "50x50", class: "user-icon" %>
              <% end %>
            </div>

            <%# ユーザー詳細中央 %>
            <div class="user-body__center">
              <%= @recipe.user.family_name + @recipe.user.given_name %>

              <div class="relationship_<%= @recipe.user.id %>">
                <%= render "relationships/relationship", follower: @recipe.user %>
              </div>
            </div>
          </div>

          <%# ユーザー詳細右側 %>
          <div class="user-body__right">
            <p>いいね</p>
            <div class="favorite_<%= @recipe.id %>">
              <%= render "favorites/favorite", favorite_base: @recipe %>
            </div>

            <p>コメント　<i class="fas fa-comment fa-lg fa-blue"></i><%= @recipe.comments.count %>件</p>

            <p>足あと　<i class="fas fa-paw fa-lg fa-brown"></i><%= @recipe.footprint %>件</p>
          </div>
        </div>

        <%# タグリンク %>
        <%= render 'shared/tag_list', tag_list: @recipe.tag_list %>

        <%# レシピ本文 %>
        <div class="show__text">
          <p><%= @recipe.body %></p>
        </div>

        <%# レシピ材料 %>
        <div class="show__food">
          <h5>材料</h5>
          <% @foods.each do |f| %>
            <p><%= f.name %></p>
          <% end %>
        </div>

        <%# レシピ作り方 %>
        <div class="show__flow">
          <h5>作り方</h5>
          <ol>
            <% @flows.each do |f| %>
              <li><%= f.body %></li>
            <% end %>
          </ol>
        </div>
      </div>

      <%# ページ右側 %>
      <div class="show_right col-12 col-sm-6 mt-3">

        <%# コメント %>
        <h4>Comment</h4>
        <% if user_signed_in? %>
          <%= form_with model: @comment, url: comments_path do |f| %>
            <%= f.text_area :body %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :recipe_id, value: @recipe.id %>
            <%= f.submit "送信" %>
          <% end %>
        <% end %>

        <div class="comment__list">
          <%= render "comments/commentlist", comments: @comments %>
        </div>
      </div>
    </div>
  </div>
</main>