config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
  }

  devise_scope :user do
    root  "homes#top"
    post  "users/guest_sign_in" => "users/sessions#create_guest", as: "user_guest_session"
  end

  get   "/users/:id/posts"        => "users#posts",       as: "users_posts"
  get   "/users/:id/recipes"      => "users#recipes",     as: "users_recipes"
  get   "/users/:id/withdrawal"   => "users#withdrawal",  as: "users_withdrawal"
  patch "/users/:id/unsubscribe"  => "users#unsubscribe", as: "users_unsubscribe"
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts
  resources :recipes
  resources :comments,        only: [:create, :destroy]
  resources :foods,           only: [:create, :destroy]
  resources :flows,           only: [:create, :destroy]
  resources :favorites,       only: [:create, :destroy]
  resources :bookmarks,       only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :items,           only: [:create, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  mount_uploader :user_image, UserImageUploader

  has_many  :posts,     dependent: :destroy
  has_many  :recipes,   dependent: :destroy
  has_many  :comments,  dependent: :destroy
  has_many  :items,     dependent: :destroy
  has_many  :bookmarks, dependent: :destroy
  has_many  :bookmark_post,   through: :bookmarks, source: :post
  has_many  :bookmark_recipe, through: :bookmarks, source: :recipe
  has_many  :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many  :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many  :followed_user,   through: :followed, source: :follower
  has_many  :follower_user,   through: :follower, source: :followed

  KATAKANA = /\A[\p{katakana}\u{30fc}]+\z/.freeze
  EMAIL = /\A\S+@\S+\.\S+\z/.freeze
  POST = /\A\d{7}\z/.freeze
  TELEPHONE = /\A\d{10,11}\z/.freeze

  validates :family_name, :given_name, :prefecture_code, :city, :street, :encrypted_password, presence: true
  validates :family_name_kana, :given_name_kana, presence: true, format: { with: KATAKANA }
  validates :postal_code, presence: true, format: { with: POST, allow_blank: true }
  validates :telephone_number, presence: true, format: { with: TELEPHONE, allow_blank: true }
  validates :email, presence: true, format: { with: EMAIL, allow_blank: true }, uniqueness: { case_sensitive: false }
  validates :is_deleted, presence: true

  def follower_by?(user)
    follower.where(followed_id: user.id).exists?
  end

  def follower_by(user)
    follower.find_by(followed_id: user.id)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  enum is_deleted: { "退会済": true, "有効": false }

  def active_for_authentication?
    super && is_deleted == "有効"
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.family_name = "Guest"
      user.given_name = "User"
      user.family_name_kana = "ゲスト"
      user.given_name_kana = "ユーザー"
      user.postal_code = 1000002
      user.prefecture_code = 13
      user.city = "千代田区"
      user.street = "1番地"
      user.telephone_number = "00000000000"
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, if: :devise_controller?
  before_action :configure_account_update_params, if: :devise_controller?
  before_action :check_guest, only: [:update, :destroy]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    result = false

    if @user.user_image.present?
      result = Vision.get_image_data(@user.user_image.url)
    else
      result = true
    end

    if result.blank?
      flash[:error] = "画像が不適切です"
      render "new"
      return
    end

    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_image, :family_name, :given_name, :family_name_kana, :given_name_kana, :postal_code, :prefecture_code, :city, :street, :building, :telephone_number, :is_deleted])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_image, :family_name, :given_name, :family_name_kana, :given_name_kana, :postal_code, :prefecture_code, :city, :street, :building, :telephone_number, :is_deleted])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  def new
    today = Time.current.at_end_of_day
    from = (today - 6.day).at_beginning_of_day
    @posts = Post.where(created_at: from...today)
    @recipes = Recipe.order(footprint: "DESC").first(3)

    # 一週間の投稿が3件未満の場合
    if @posts.count < 3
      @posts = Post.all
    end

    @posts = @posts.order(footprint: "DESC").first(3)
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  def create_guest
    user = User.guest
    sign_in user
    redirect_to root_path, success: "ゲストログインしました"
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.valid_password?(params[:user][:password]) && @user.active_for_authentication? == false
        redirect_to new_user_session_path
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :withdrawal, :unsubscribe]
  before_action :check_guest, only: [:update, :unsubscribe]

  def index
    @users = User.where(is_deleted: "有効")

    if params[:search_family_name] || params[:search_given_name]
      @users = @users.where("family_name LIKE ?", "%#{params[:search_family_name]}%")
      @users = @users.where("given_name LIKE ?", "%#{params[:search_given_name]}%")

      if @users.count == 0
        @title = "検索結果がありません"
      else
        @title = "検索結果：#{params[:search_family_name]}　#{params[:search_given_name]}"
      end

    elsif params[:followed]
      @users = current_user.followed_user

      if current_user.followed_user.present?
        @title = "フォロー"
      else
        @title = "フォローユーザーがいません"
      end

    elsif params[:follower]
      @users = current_user.follower_user

      if current_user.follower_user.present?
        @title = "フォロワー"
      else
        @title = "フォロワーがいません"
      end

    else
      @title = "ALL"
    end

    @users = @users.order(id: "DESC").page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])

    if @user.is_deleted == "退会済"
      flash[:error] = "対象のユーザーは退会済です"
      redirect_to users_path
    end

    if @user == current_user
      @item = Item.new
      @items = current_user.items
    else
      redirect_to users_posts_path(params[:id])
    end
  end

  def posts
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id]).page(params[:page]).per(9)
  end

  def recipes
    @user = User.find(params[:id])
    @recipes = Recipe.where(user_id: params[:id]).page(params[:page]).per(9)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(current_user.id)
    @user.user_image = user_params[:user_image]
    result = false

    if user_params[:user_image].present?
      result = Vision.get_image_data(@user.user_image.url)
    else
      result = true
    end

    if result.blank?
      flash.now[:error] = "画像が不適切です"
      render "edit"
      return
    end

    if @user.update(user_params)
      flash[:success] = "編集を保存しました"
      redirect_to user_path(current_user.id)
    else
      flash.now[:error] = "保存に失敗しました"
      render "edit"
    end
  end

  def withdrawal
  end

  def unsubscribe
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    redirect_to new_user_session_path
  end

  private

  def user_params
    params.require(:user).permit(:user_image, :family_name, :given_name, :family_name_kana,
                                 :given_name_kana, :email, :postal_code, :prefecture_code, :city, :street, :building, :telephone_number)
  end

  def check_user
    item = Item.find(params[:id])
    user = User.find(item.user_id)
    redirect_back fallback_location: user_path(current_uer.id) unless user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage_sidebar.html.erb
<%# マイページサイドバー %>
<h4>My Page</h4>
<%= image_tag current_user.user_image.thumb.url, size: "70x70", class: "user-icon mb-1" %>
<p class="mb-1"><%= current_user.family_name + current_user.given_name %></p>
<p class="mb-4"><%= current_user.family_name_kana + current_user.given_name_kana %></p>
<%= link_to "プロフィール編集", edit_user_path(current_user.id), class: "btn_blue_mini mb-1" %>
<%= link_to "follow user", users_path(followed: current_user.followed), class: "btn_blue_mini mb-1" %>
<%= link_to "follower", users_path(follower: current_user.follower), class: "btn_blue_mini mb-1" %>
<%= link_to "My Posts", users_posts_path(current_user.id), class: "btn_blue_mini mb-1" %>
<%= link_to "Posts BM", posts_path(bookmarks: current_user.bookmarks), class: "btn_blue_mini mb-1" %>
<%= link_to "New Post", new_post_path, class: "btn_green_mini mb-1" %>
<%= link_to "My Camping Meals", users_recipes_path(current_user.id), class: "btn_blue_mini mb-1" %>
<%= link_to "Camping Meals BM", recipes_path(bookmarks: current_user.bookmarks), class: "btn_blue_mini mb-1" %>
<%= link_to "New Camping Meal", new_recipe_path, class: "btn_green_mini mb-1" %>

app/views/users/_show_sidebar.html.erb
<%# ユーザー詳細サイドバー %>
<h4>User</h4>
<%= image_tag user.user_image.thumb.url, size: "70x70", class: "user-icon mb-1" %>
<p class="mb-1"><%= user.family_name + user.given_name %></p>
<p class="mb-4"><%= user.family_name_kana + user.given_name_kana %></p>

<%# フォローリンク %>
<div class="relationship_<%= user.id %>">
  <%= render "relationships/relationship", follower: user %>
</div>

<%= link_to "Posts", users_posts_path(user.id), class: "btn_blue mt-1" %>
<%= link_to "Camping Meals", users_recipes_path(user.id), class: "btn_blue mt-1" %>

app/views/users/_sidebar.html.erb
<%# 名前検索フォーム %>
<%= form_with url: users_path, method: :get, local: true, class: "form mt-5" do |f| %>
  <h6 class="pl-2 mb-3">名前検索</h6>
  <%= f.text_field :search_family_name, placeholder: "（例）山田", class: "mb-3" %>
  <%= f.text_field :search_given_name, placeholder: "（例）太郎" %>
  <%= f.submit "検索", class: "btn_blue py-1 mt-3" %>
<% end %>

app/views/users/edit.html.erb
<%# 会員情報編集ページ %>
<main class="main__background main__background__user">
  <div class="container">
    <div class="row">
      <%= form_with model: @user, local: true, class: "user-form my-5" do |f| %>
        <h5 class="mb-5">会員情報編集</h5>

        <div class="user-icon__wrapper mb-3">
          <%= image_tag @user.user_image.thumb.url, size: "70x70", class: "user-icon img_prev" %>
          <button>
            <%= f.file_field :user_image, class: "img" %>
          </button>
        </div>

        <table>
          <tbody>
            <tr>
              <td><%= f.label :family_name, "名前", class: "need" %></td>
              <td>
                <%= f.text_field :family_name, autofocus: true, autocomplete: "family_name" %>
                <% if @user.errors.include?(:family_name) || @user.errors.include?(:given_name) %>
                  <span class="red"><%= @user.errors.full_messages_for(:family_name).first %></span>
                <% end %>
              </td>
              <td>
                <%= f.text_field :given_name, autofocus: true, autocomplete: "given_name", class: "need" %>
                <% if @user.errors.include?(:family_name) || @user.errors.include?(:given_name) %>
                  <span class="red"><%= @user.errors.full_messages_for(:given_name).first %></span>
                <% end %>
              </td>
            </tr>

            <tr>
              <td><%= f.label :family_name_kana, "フリガナ", class: "need" %></td>
              <td>
                <%= f.text_field :family_name_kana, autofocus: true, autocomplete: "family_name_kana" %>
                <% if @user.errors.include?(:family_name_kana) || @user.errors.include?(:given_name_kana) %>
                  <span class="red"><%= @user.errors.full_messages_for(:family_name_kana).first %></span>
                <% end %>
              </td>
              <td>
                <%= f.text_field :given_name_kana, autofocus: true, autocomplete: "given_name_kana" %>
                <% if @user.errors.include?(:family_name_kana) || @user.errors.include?(:given_name_kana) %>
                  <span class="red"><%= @user.errors.full_messages_for(:given_name_kana).first %></span>
                <% end %>
              </td>
            </tr>

            <tr>
              <td><%= f.label :email, "メールアドレス", class: "need" %></td>
              <td>
                <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
                <% if @user.errors.include?(:email) %>
                  <span class="red"><%= @user.errors.full_messages_for(:email).first %></span>
                <% end %>
              </td>
            </tr>

            <tr>
              <td><%= f.label :postal_code, "郵便番号(ハイフンなし)", class: "need" %></td>
              <td>
                <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
                <% if @user.errors.include?(:postal_code) %>
                  <span class="red"><%= @user.errors.full_messages_for(:postal_code).first %></span>
                <% end %>
              </td>
            </tr>

            <tr>
              <td><%= f.label :prefecture_code, "都道府県", class: "need" %></td>
              <td>
                <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :name, :name, autofocus: true %>
                <% if @user.errors.include?(:prefecture_code) %>
                  <span class="red"><%= @user.errors.full_messages_for(:prefecture_code).first %></span>
                <% end %>
              </td>
            </tr>

            <tr>
              <td><%= f.label :city, "市区町村", class: "need" %></td>
              <td>
                <%= f.text_field :city, autofocus: true, autocomplete: "city" %>
                <% if @user.errors.include?(:city) %>
                  <span class="red"><%= @user.errors.full_messages_for(:city).first %></span>
                <% end %>
              </td>
            </tr>

            <tr>
              <td><%= f.label :street, "番地", class: "need" %></td>
              <td>
                <%= f.text_field :street, autofocus: true, autocomplete: "street" %>
                <% if @user.errors.include?(:street) %>
                  <span class="red"><%= @user.errors.full_messages_for(:street).first %></span>
                <% end %>
              </td>
            </tr>

            <tr>
              <td><%= f.label :building, "建物" %></td>
              <td><%= f.text_field :building, autofocus: true, autocomplete: "building" %></td>
            </tr>

            <tr>
              <td><%= f.label :telephone_number, "電話番号(ハイフンなし)", class: "need" %></td>
              <td>
                <%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %>
                <% if @user.errors.include?(:telephone_number) %>
                  <span class="red"><%= @user.errors.full_messages_for(:telephone_number).first %></span>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>

        <div class="user-form__field">
          <%= f.submit "編集内容を保存する", class: "btn_blue" %>
          <%= link_to "削除", users_withdrawal_path(current_user.id), class: "btn_red ml-3" %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main class="main__background main__background__user">
  <div class="container">
    <div class="row">
      <%# ユーザー一覧サイドバー %>
      <div class="user-sidebar col-12 col-sm-2 my-3 bg-white">
        <%= render "sidebar" %>
      </div>

      <div class="users col-12 col-sm-10 my-3">
        <%# タイトルバー %>
        <div class="titlebar bg-white">
          <h4 class="m-3">Users　<%= @title %></h4>
        </div>
        
        <%# ユーザー一覧 %>
        <div class="user-index bg-white">
          <% @users.each do |u| %>
            <div class="user-body py-2">
              <div class="user-body_left d-flex">
                <%= link_to user_path(u.id) do %>
                  <%= image_tag u.user_image.thumb.url, size: "60x60", class: "user-icon mx-4" %>
                <% end %>

                <div class="user-body__text mx-4">
                  <p><%= u.family_name + u.given_name %></p>

                  <div class="relationship_<%= u.id %>">
                    <%= render "relationships/relationship", follower: u %>
                  </div>
                </div>
              </div>

              <div class="user-body_center d-flex">
                <div class="follow-count_<%= u.id %>">
                  <%= render "relationships/relationship_count", follow: u %>
                </div>
              </div>

              <div class="post-count__wrapper mx-4">
                <div class="post-count mb-2">
                  <span><i class="fas fa-campground fa-green fa-size__m"></i></span>
                  <p>Posts</p>
                  <p><%= u.posts.count %>件</p>
                </div>
                <div class="post-count">
                  <span><i class="fas fa-utensils fa-brown fa-size__m"></i></span>
                  <p>Camping Meals</p>
                  <p><%= u.recipes.count %>件</p>
                </div>
              </div>
            </div>
          <% end %>
        </div>

        <%= paginate @users %>
      </div>
    </div>
  </div>
</main>

app/views/users/posts.html.erb
<main class="main__background main__background__post">
  <div class="container">
    <div class="row">
      <%# マイページサイドバー %>
      <div class="user__info col-12 col-sm-2 bg-white my-4 py-4">
        <% if @user == current_user %>
          <%= render "mypage_sidebar", user: current_user %>
        <% else %>
          <%= render "show_sidebar", user: @user %>
        <% end %>
      </div>

      <%# マイページ投稿一覧メイン %>
      <div class="post-recipe-index col-12 col-sm-10 bg-white p-4 my-4">
        <%= render "/posts/index", title: @title, posts: @posts %>
      </div>
    </div>
  </div>
</main>

app/views/users/recipes.html.erb
<main class="main__background main__background__recipe">
  <div class="container">
    <div class="row">
      <%# マイページサイドバー %>
      <div class="user__info col-2 bg-white my-4 py-4">
        <% if @user == current_user %>
          <%= render "mypage_sidebar", user: current_user %>
        <% else %>
          <%= render "show_sidebar", user: @user %>
        <% end %>
      </div>

      <%# マイページレシピ一覧メイン %>
      <div class="post-recipe-index col-10 bg-white p-4 my-4">
        <%= render "/recipes/index", title: @title, recipes: @recipes %>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<%# マイページ %>
<main class="main__background main__background__user">
  <div class="container">
    <div class="row">
      <%# マイページサイドバー %>
      <div class="user__info col-12 col-sm-2 bg-white my-4 py-4">
        <%= render "mypage_sidebar", user: @user %>
      </div>

      <%# マイページ持ち物リスト %>
      <div class="current-user__body col-12 col-sm-10 my-4">
        <div class="items bg-white p-4">
          <div class="item__form">
            <h4>持ち物リスト</h4>

            <%# 持ち物リスト入力フォーム %>
            <%= form_with model: @item, url: items_path, class: "form" do |f| %>
              <%= f.label :name, "持ち物：" %>
              <%= f.text_field :name %>
              <%= f.submit "登録", class: "btn_blue" %>
            <% end %>
          </div>

          <%# 持ち物リスト表示画面 %>
          <div class="item__list mt-4">
            <%= render "items/itemlist", items: @items %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/withdrawal.html.erb
<%# 退会確認ページ %>
<main>
  <div class="container">
    <div class="row">
      <div class="withdrawal">
        <h2>本当に退会しますか？</h2>
        <p>
          退会すると会員情報やブックマーク、持ち物リストが閲覧できなくなります。<br>
          退会する場合は「退会する」をクリックしてください
        </p>
        <div class="withdrawal-btn mt-4">
          <%= link_to "退会しない", user_path(current_user.id), class: "btn_blue" %>
          <%= link_to "退会する", users_unsubscribe_path(current_user.id), method: :patch, class: "btn_red" %>
        </div>
      </div>
    </div>
  </div>
</main>