config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
  }

  devise_scope :user do
    root  "homes#top"
    post  "users/guest_sign_in" => "users/sessions#create_guest", as: "user_guest_session"
  end

  get   "/users/:id/posts"        => "users#posts",       as: "users_posts"
  get   "/users/:id/recipes"      => "users#recipes",     as: "users_recipes"
  get   "/users/:id/withdrawal"   => "users#withdrawal",  as: "users_withdrawal"
  patch "/users/:id/unsubscribe"  => "users#unsubscribe", as: "users_unsubscribe"
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts
  resources :recipes
  resources :comments,        only: [:create, :destroy]
  resources :foods,           only: [:create, :destroy]
  resources :flows,           only: [:create, :destroy]
  resources :favorites,       only: [:create, :destroy]
  resources :bookmarks,       only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :items,           only: [:create, :update, :destroy]
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to  :user
  belongs_to  :post,    optional: true
  belongs_to  :recipe,  optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to  :user
  belongs_to  :post,    optional: true
  belongs_to  :recipe,  optional: true

  validates   :body,    presence: true, length: { maximum: 50 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to  :user
  belongs_to  :post,    optional: true
  belongs_to  :recipe,  optional: true

  def favorite_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def fovorite_by(user)
    favorites.where(user_id: user.id)
  end
end

app/models/flow.rb
class Flow < ApplicationRecord
  belongs_to  :recipe

  validates   :body, presence: true, length: { maximum: 50 }
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to  :recipe

  validates   :name, presence: true, length: { maximum: 20 }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to  :user

  validates   :name,    presence: true, length: { maximum: 20 }
  validates   :status,  presence: true

  enum status: {
    "未所持": 0,
    "所持済": 1,
    "要購入": 2,
  }

  # 所持ステータスの変更
  def change_status
    case status
    when "未所持"
      update(status: "所持済")
    when "所持済"
      update(status: "要購入")
    when "要購入"
      update(status: "未所持")
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable

  mount_uploaders :post_images, PostImagesUploader

  belongs_to  :user

  has_many    :favorites,       dependent: :destroy
  has_many    :comments,        dependent: :destroy
  has_many    :bookmarks,       dependent: :destroy
  has_many    :favorite_users,  through: :favorites, source: :user
  has_many    :bookmark_users,  through: :bookmarks, source: :user

  validates   :post_images, :footprint, presence: true
  validates   :title, presence: true, length: { maximum: 20 }
  validates   :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def favorited_by(user)
    favorites.find_by(user_id: user.id)
  end

  def bookmark_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def bookmark_by(user)
    bookmarks.find_by(user_id: user.id)
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  acts_as_taggable

  mount_uploaders :recipe_images, RecipeImagesUploader

  belongs_to  :user

  has_many    :favorites,       dependent: :destroy
  has_many    :comments,        dependent: :destroy
  has_many    :bookmarks,       dependent: :destroy
  has_many    :foods,           dependent: :destroy
  has_many    :flows,           dependent: :destroy
  has_many    :favorite_users,  through: :favorites, source: :user
  has_many    :bookmark_users,  through: :bookmarks, source: :user

  validates   :recipe_images, :footprint, :status, presence: true
  validates   :title, presence: true, length: { maximum: 20 }
  validates   :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def favorited_by(user)
    favorites.find_by(user_id: user.id)
  end

  def bookmark_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def bookmark_by(user)
    bookmarks.find_by(user_id: user.id)
  end

  enum status: { "非公開": false, "公開": true }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to  :follower,  class_name: "User", foreign_key: "follower_id"
  belongs_to  :followed,  class_name: "User", foreign_key: "followed_id"
end

app/models/tagentry.rb
class Tagentry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  mount_uploader :user_image, UserImageUploader

  has_many  :posts,     dependent: :destroy
  has_many  :recipes,   dependent: :destroy
  has_many  :comments,  dependent: :destroy
  has_many  :items,     dependent: :destroy
  has_many  :bookmarks, dependent: :destroy
  has_many  :bookmark_post,   through: :bookmarks, source: :post
  has_many  :bookmark_recipe, through: :bookmarks, source: :recipe
  has_many  :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many  :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many  :followed_user,   through: :followed, source: :follower
  has_many  :follower_user,   through: :follower, source: :followed

  KATAKANA = /\A[\p{katakana}\u{30fc}]+\z/.freeze
  EMAIL = /\A\S+@\S+\.\S+\z/.freeze
  POST = /\A\d{7}\z/.freeze
  TELEPHONE = /\A\d{10,11}\z/.freeze

  validates :family_name, :given_name, :prefecture_code, :city, :street, :encrypted_password, presence: true
  validates :family_name_kana, :given_name_kana, presence: true, format: { with: KATAKANA }
  validates :postal_code, presence: true, format: { with: POST, allow_blank: true }
  validates :telephone_number, presence: true, format: { with: TELEPHONE, allow_blank: true }
  validates :email, presence: true, format: { with: EMAIL, allow_blank: true }, uniqueness: { case_sensitive: false }
  validates :is_deleted, presence: true

  def follower_by?(user)
    follower.where(followed_id: user.id).exists?
  end

  def follower_by(user)
    follower.find_by(followed_id: user.id)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  enum is_deleted: { "退会済": true, "有効": false }

  def active_for_authentication?
    super && is_deleted == "有効"
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.family_name = "Guest"
      user.given_name = "User"
      user.family_name_kana = "ゲスト"
      user.given_name_kana = "ユーザー"
      user.postal_code = 1000002
      user.prefecture_code = 13
      user.city = "千代田区"
      user.street = "1番地"
      user.telephone_number = "00000000000"
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_background.html.erb
<%# トップページ背景 %>
<div class="container-fluid">
  <div class="row">
    <div class="background d-flex h-100">
      <div class="background__image_item col-4 p-0">
        <%= video_tag "/assets/main-visual-4c79b6d13387b6f06bd604e09f65b65d5670a2f4a3f40a4f3b9b8ebd830662ce.mp4", autoplay: true, loop: true, muted: true, class: "h-100" %>
      </div>
      <div class="background__image_item col-12 col-sm-4 p-0"></div>
      <div class="background__image_item col-4 p-0"></div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
 <%# フラッシュメーセージ領域 %>
 <div class="notifications">
  <% flash.each do |message_type, message| %>
    <%= content_tag :div, message, class: message_type %>
  <% end %>
 </div>

app/views/shared/_footer.html.erb
<%# フッター %>
<p class="pt-4 pb-4 m-0 text-center">©︎Camping style</p>

app/views/shared/_header_login_after.html.erb
<%# ログイン前ヘッダー %>
<nav class="navbar navbar-expand-lg navbar-light bg-light w-100">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav ml-auto mr-3 mt-2 mt-lg-0 ">
      <li class="nav-item dropdown">
        <%= link_to "Mypage", user_path(current_user.id), class: "nav-link dropdown-taggle",  id: "navbarDropdown", role: "button", "data-toggle": "dropdown", "aria-haspopup": "true", "aria-expanded": "false" %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Mypage", user_path(current_user.id), class: "dropdown-item" %>
          <%= link_to "プロフィール編集", edit_user_path(current_user.id), class: "dropdown-item" %>
          <%= link_to "follow user", users_path(followed: current_user.followed), class: "dropdown-item" %>
          <%= link_to "follower", users_path(follower: current_user.follower), class: "dropdown-item" %>
          <%= link_to "My Posts", users_posts_path(current_user.id), class: "dropdown-item" %>
          <%= link_to "Posts BM", posts_path(bookmarks: current_user.bookmarks), class: "dropdown-item" %>
          <%= link_to "New Post", new_post_path, class: "dropdown-item" %>
          <%= link_to "My Camping Meals", users_recipes_path(current_user.id), class: "dropdown-item" %>
          <%= link_to "Camping Meals BM", recipes_path(bookmarks: current_user.bookmarks), class: "dropdown-item" %>
          <%= link_to "New Camping Meal", new_recipe_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Posts", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Camping Meals", recipes_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_header_login_before.html.erb
<%# ログイン前ヘッダー %>
<nav class="navbar navbar-expand-lg navbar-light bg-light w-100">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav ml-auto mr-3 mt-2 mt-lg-0 ">
      <li class="nav-item">
        <%= link_to "About", new_user_session_path(anchor: 'about'), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Posts", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Camping Meals", recipes_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_index_sidebar.html.erb
<%# タイトル検索フォーム %>
<% if /post/ =~ request.fullpath %>
  <%= form_with url: posts_path, method: :get, local: true, class: "form mt-5" do |f| %>
    <h6 class="pl-2 mb-3">タイトル検索</h6>
    <%= f.text_field :search, placeholder: "（例）焚き火" %>
    <%= f.submit "検索", class: "btn_blue py-1 mt-3" %>
  <% end %>
<% else %>
  <%= form_with url: recipes_path, method: :get, local: true, class: "form mt-5" do |f| %>
    <h6 class="pl-2 mb-3">タイトル検索</h6>
    <%= f.text_field :search, placeholder: "（例）モーニング" %>
    <%= f.submit "検索", class: "btn_blue py-1 mt-3" %>
  <% end %>
<% end %>

<%# タグ検索フォーム %>
<h6 class="tag-title pl-2 mt-5">タグ検索</h6>
<div class="tag-sidebar">
  <table>
    <tbody>
      <% if /post/ =~ request.fullpath %>
        <% tags.each do |tag| %>
          <tr><td><%= link_to tag.name, posts_path(tag_name: tag.name) %></td></tr>
        <% end %>
      <% else %>
        <% tags.each do |tag| %>
          <tr><td><%= link_to tag.name, recipes_path(tag_name: tag.name) %></td></tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_key-visual.html.erb
<%# キービジュアル %>
<%# 背景 %>
<%= render "/shared/background" %>

<div class="container-fluid">
  <div class="row">
    <div class="key-visual w-100 mb-5">
      <%# タイトル %>
      <div class="key-visual__title d-flex align-items-center h-100">
        <h1 class="d-flex align-items-center justify-content-center w-100 bg-white">
          <span>C</span>
          <span>a</span>
          <span>m</span>
          <span>p</span>
          <span>i</span>
          <span>n</span>
          <span>g</span>&nbsp;
          <span>s</span>
          <span>t</span>
          <span>y</span>
          <span>l</span>
          <span>e</span>
        </h1>
      </div>

      <%# ログインフォーム %>
      <% unless user_signed_in? %>
        <%= render "devise/shared/login_form" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_tag_list.html.erb
<%# 投稿のタグ欄 %>
<% if /post/ =~ request.fullpath %>
  <% tag_list.each do |tag| %>
    <%= link_to posts_path(tag_name: tag), class: "btn_blue_mini" do %>
      <span><%= tag %></span>
    <% end %>
  <% end %>

<%# レシピのタグ欄 %>
<% else %>
  <% tag_list.each do |tag| %>
    <%= link_to recipes_path(tag_name: tag), class: "btn_blue_mini" do %>
      <span><%= tag %></span>
    <% end %>
  <% end %>
<% end %>